### ISSUE TITLE
Android  release  env  does not work

### ISSUE THREAD

**Issue by kang-breakfly** [boskokg/flutter_blue_plus#215]
My project debug env and profile env is ok,but release env bluetoothState is null.

![28271678169940_ pic](https://user-images.githubusercontent.com/28882894/223341612-88268c14-1843-4342-a8cb-06d72425cf44.jpg)
How to solve this problem

**Comment by kang-breakfly** [comment]
E/flutter (13584): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(startScan, Field androidScanMode_ for l.g0 not found. Known fields are [private int l.g0.h, private m.b0$i l.g0.i, private boolean l.g0.j, private m.b0$i l.g0.k, private static final l.g0 l.g0.l, private static volatile m.a1 l.g0.m], java.lang.RuntimeException: Field androidScanMode_ for l.g0 not found. Known fields are [private int l.g0.h, private m.b0$i l.g0.i, private boolean l.g0.j, private m.b0$i l.g0.k, private static final l.g0 l.g0.l, private static volatile m.a1 l.g0.m]
E/flutter (13584):      at m.v0.n0(Unknown Source:72)
E/flutter (13584):      at m.v0.T(Unknown Source:655)
E/flutter (13584):      at m.v0.R(Unknown Source:12)
E/flutter (13584):      at m.k0.e(Unknown Source:60)
E/flutter (13584):      at m.k0.a(Unknown Source:49)
E/flutter (13584):      at m.d1.d(Unknown Source:17)
E/flutter (13584):      at m.d1.e(Unknown Source:4)
E/flutter (13584):      at m.z$a.z(Unknown Source:9)
E/flutter (13584):      at m.z$a.y(Unknown Source:4)
E/flutter (13584):      at m.z$a.o(Unknown Source:0)
E/flutter (13584):      at m.a$a.n(Unknown Source:2)
E/flutter (13584):      at l.i.N(Unknown Source:10)
E/flutter (13584):      at l.i.E(Unknown Source:2)
E/flutter (13584):      at l.i.i(Unknown Source:0)
E/flutter (13584):      at l.d.a(Unknown Source:6)
E/flutter (13584):      at l.i.w(Unknown Source:49)
E/flutter (13584):      at l.i.F(Unknown Source:16)
E/flutter (13584):      at l.i.j(Unknown Source:0)
E/flutter (13584):      at l.e.a(Unknown Source:6)
E/flutter (13584):      at l.i.B(Unknown Source:11)
E/flutter (13584):      at l.i.o(Unknown Source:0)
E/flutter (13584):      at l.h.a(Unknown Source:4)
E/flutter (13584):      at l.i.a(Unknown Source:28)
E/flutter (13584):      at io.flutter.embedding.engine.c$c.h(Unknown Source:20)
E/flutter (13584):      at io.flutter.embedding.engine.c.a(Unknown Source:13)
E/flutter (13584):      at io.flutter.embedding.android.e.x(Unknown Source:59)
E/flutter (13584):      at io.flutter.embedding.android.d.onRequestPermissionsResult(Unknown Source:10)
E/flutter (13584):      at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7951)
E/flutter (13584):      at android.app.Activity.dispatchActivityResult(Activity.java:7801)
E/flutter (13584):      at android.app.ActivityThread.deliverResults(ActivityThread.java:5202)
E/flutter (13584):      at android.app.ActivityThread.handleSendResult(ActivityThread.java:5251)
E/flutter (13584):      at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/flutter (13584):      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/flutter (13584):      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/flutter (13584):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
E/flutter (13584):      at android.os.Handler.dispatchMessage(Handler.java:112)
E/flutter (13584):      at android.os.Looper.loop(Looper.java:216)
E/flutter (13584):      at android.app.ActivityThread.main(ActivityThread.java:7779)
E/flutter (13584):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (13584):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/flutter (13584):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
E/flutter (13584): , null)
E/flutter (13584): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter (13584): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315)
E/flutter (13584): <asynchronous suspension>
E/flutter (13584): #2      FlutterBluePlus.scan (package:flutter_blue_plus/src/flutter_blue_plus.dart:160)
E/flutter (13584): <asynchronous suspension>
E/flutter (13584): #3      _httpConnectionHook.<anonymous closure> (dart:_http/embedder_config.dart:21)
E/flutter (13584): <asynchronous suspension>
E/flutter (13584):

**Comment by kang-breakfly** [comment]
minifyEnabled false 
             shrinkResources false
             this mast false
