### ISSUE TITLE
The WRITE property is not supported by this BLE characteristic, null, null)

### ISSUE THREAD

**Issue by bigpig911** [boskokg/flutter_blue_plus#392]
I/flutter (24709): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (24709): │ ⚠️  send===>1:指令请求超时Exception: PlatformException(write_characteristic_error, The WRITE property is not supported by this BLE characteristic, null, null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
I/flutter (24709): │ ⚠️ #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #2      BluetoothCharacteristic.write.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:167:9)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:311:7)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #4      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:142:5)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #5      BluetoothConnectManager.writeCommand (package:fj_application/utils/bluetooth/bluetooth_connect_utils.dart:248:5)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #6      EnergyPageCubit.sendMessage (package:fj_application/bloc/energy_page_cubit.dart:273:9)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️ #7      EnergyPageCubit.queryOutputInterfaceInfo.<anonymous closure> (package:fj_application/bloc/energy_page_cubit.dart:360:22)
I/flutter (24709): │ ⚠️ <asynchronous suspension>
I/flutter (24709): │ ⚠️

**Comment by chipweinberger** [comment]
should be fixed in 1.8.1
