### ISSUE TITLE
While writing in charcateristic there is an issue with PlatformException(androidException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference[Bug]: 

### ISSUE THREAD

**Issue by Snofkin** [boskokg/flutter_blue_plus#433]
### FlutterBluePlus Version

1.10.10

### What OS?

Android

### OS Version

10

### What happened?

Here is how i write 
`onWritePressed: () async {   print(c.uuid);   try {     await c.write(       [0x29],     );     if (c.properties.read) {       await c.read();     }   } catch (e) {     print("Write Error:==>$e");   } }, `

![Screenshot 2023-07-26 at 1 23 27 PM](https://github.com/boskokg/flutter_blue_plus/assets/25322078/7b028511-6778-4f0f-b556-b7d502279c1c)

### Logs

```shell
D/[FBP-Android](10894): [FBP-Android] onMethodCall: writeCharacteristic
I/flutter (10894): Write Error:==>PlatformException(androidException, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
I/flutter (10894): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:661)
I/flutter (10894): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (10894): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (10894): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (10894): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (10894): 	at android.os.Handler.handleCallback(Handler.java:883)
I/flutter (10894): 	at android.os.Handler.dispatchMessage(Handler.java:100)
I/flutter (10894): 	at android.os.Looper.loop(Looper.java:359)
I/flutter (10894): 	at android.a
```

**Comment by chipweinberger** [comment]
fixed: 1.11.4
