### ISSUE TITLE
[Question]: locateGatt failed. have you connected first?

### ISSUE THREAD

**Issue by umuttsaltan** [boskokg/flutter_blue_plus#471]
### Ask your question

Yesterday i opened a issue because of that problem. #465 

I tried the solution but it didn't work, didn't solve my problem.

```
PlatformException(androidException, java.lang.Exception: locateGatt failed. have you connected first?, java.lang.Exception: locateGatt failed. have you connected first?
I/flutter (23283):      at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.locateGatt(FlutterBluePlusPlugin.java:1038)
I/flutter (23283):      at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:477)
I/flutter (23283):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
I/flutter (23283):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (23283):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/flutter (23283):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (23283):      at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (23283):      at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (23283):      at android.os.Looper.loop(Looper.java:223)
```

Problem is occurs on Android, on IOS discoverServices works with no problem. 

BLE Device connection step by step :

1. Scan devices
2. Find the specific device from remoteId
3. Connect and then discoverServices

I can see from BLE device, connection is successful but discoverServices not working.

**Comment by chipweinberger** [comment]
thanks. please file a bug report. Not a question.

The bug report will include all the info we need to help you. Also, we need _more_ logs.
