### ISSUE TITLE
[Question]: Current project stability

### ISSUE THREAD

**Issue by baconcheese113** [boskokg/flutter_blue_plus#480]
Hey @chipweinberger first off I want to say **THANK YOU** for your awesome contributions this year! It's exciting to see flutter_blue get active development for the first time in years!

My question is about the huge rewrite that the package is going through, is there any way for us to follow the roadmap or provide feedback about some API design choices. I just recently noticed that an upgrade from 1.4.0 -> 1.5.2 broke my over-the-air update logic with the following error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(write_characteristic_error, no instance of BluetoothGatt, have you connected first?, null, null)
E/flutter ( 2038): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 2038): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 2038): <asynchronous suspension>
E/flutter ( 2038): #2      BluetoothCharacteristic.write.<anonymous closure> (package:flutter_blue_plus/src/bluetooth_characteristic.dart:168:17)
E/flutter ( 2038): <asynchronous suspension>
E/flutter ( 2038): #3      _Mutex.synchronized (package:flutter_blue_plus/src/utils.dart:314:13)
E/flutter ( 2038): <asynchronous suspension>
E/flutter ( 2038): #4      BluetoothCharacteristic.write (package:flutter_blue_plus/src/bluetooth_characteristic.dart:141:9)
E/flutter ( 2038): <asynchronous suspension>
```

I'm sure that upgrading to the latest version and debugging my project a bit will resolve this, but since BLE exchanges are a tricky thing to write automated tests for I'm wondering if the latest changes would be more appropriate in a `beta` branch? Or maybe breaking changes could be separated from the other bug fixes and released as a major version?

Also would it help to include integration tests that could ensure the example app still works between updates, or documentation outlining the best-practices for mocking FlutterBluePlus? If so, I wouldn't mind submitting a PR to include it.

My approach is to funnel all BLE commands through a BLE provider, which I then mock during tests. I'd be curious to hear other approaches.

```dart
// main.dart
void main({BleProvider? bleProvider}) async {
...
// if bleProvider is null then create (a real) one
```
```dart
// my_test.dart
    setUp(() {
      final mockBleProvider = FakeBleProvider();
      app.main(bleProvider: mockBleProvider);
    });
```
```dart
// ble_provider.dart
class BleProvider extends ChangeNotifier {
  bool scanning = false;
  bool _isDisposed = false;

  Future<bool> tryConnect(BluetoothDevice? hub) async {
    if (hub == null) return false;
    if (!await FlutterBluePlus.instance.isOn) return false;
    // Needed for older devices
    BluetoothDeviceState? state;
    final stateListener = hub.state.listen((newState) {
      print("New state is $newState");
      state = newState;
    });
    await hub.connect(timeout: const Duration(seconds: 10));
    state ??= await Future<BluetoothDeviceState?>.value(hub.state.last).timeout(const Duration(seconds: 1));
    stateListener.cancel();
    final isConnected = state == BluetoothDeviceState.connected;
    return isConnected;
  }

  Future<BluetoothDevice?> scan({
    required bool Function(BluetoothDevice, String?) onScanResult,
    List<Guid> services = const [],
    Duration? timeout = const Duration(seconds: 20),
  }) async {
    if (!await FlutterBluePlus.instance.isOn) return null;
    if (scanning) await stopScan();
    scanning = true;
    notifyListeners();
    BluetoothDevice? ret;
    await for (final r in FlutterBluePlus.instance.scan(timeout: timeout, withServices: services)) {
      final advMacRaw = r.advertisementData.manufacturerData[0];
      final advMacStr = advMacRaw != null
          ? List.generate(6, (idx) => advMacRaw[idx].toRadixString(16).padLeft(2, '0')).join(":")
          : null;
      if (onScanResult(r.device, advMacStr)) {
        ret = r.device;
        break;
      }
    }
    await FlutterBluePlus.instance.stopScan();
    scanning = false;
    notifyListeners();
    return ret;
  }

  Future<void> stopScan() async {
    if (!await FlutterBluePlus.instance.isOn) return;
    await FlutterBluePlus.instance.stopScan();
    scanning = false;
    notifyListeners();
  }
...
}
```

**Comment by chipweinberger** [comment]
My updates are done at this point.

1.12.x should be very stable, and won't have many changes going forward.

Doing testing on a beta branch would be great for users of course, but there would be no upside for me. I contribute to flutter blue mainly for selfish reasons of course :)

I'd recommend staying on 1.4.x if you do not want to contribute towards testing.

That
