### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodError: No virtual method getOrDefault

### ISSUE THREAD

**Issue by Eashubh128** [boskokg/flutter_blue_plus#523]
### FlutterBluePlus Version

^1.12.9

### Flutter Version

3.10.4

### What OS?

Android, All

### OS Version

FireOS version 5.7.0.0

### What happened?

I am running my application on a kindle device running on FireOS 5.7.0.0 , when i try to scan nerarby ble devices the application closes .
  java.lang.NoSuchMethodError: No virtual method getOrDefault.

### Logs

```shell
D/Android: [Awesome Notifications](  532): App is now Foreground (LifeCycleManager:94)
I/flutter (  532): [FBP] <setLogLevel> args: 5
[log] check prev connections called
I/flutter (  532): [FBP] <getConnectedSystemDevices> args: null
D/[FBP-Android](  532): [FBP-Android] onMethodCall: setLogLevel
D/[FBP-Android](  532): [FBP-Android] onMethodCall: getConnectedSystemDevices
D/BluetoothManager(  532): getConnectedDevices
I/flutter (  532): [FBP] <setLogLevel> result: null
I/flutter (  532): [FBP] <getConnectedSystemDevices> result: {devices: []}
I/Kernel  (  532): [47535.518267]-(0)[612:1.ui]dpi vsync
I/flutter (  532): 1
I/flutter (  532): [FBP] <setLogLevel> args: 5
D/[FBP-Android](  532): [FBP-Android] onMethodCall: setLogLevel
I/flutter (  532): [FBP] <setLogLevel> result: null
I/flutter (  532): [FBP] <getAdapterState> args: null
D/[FBP-Android](  532): [FBP-Android] onMethodCall: getAdapterState
I/flutter (  532): [FBP] <getAdapterState> result: {adapter_state: 4}
I/flutter (  532): [FBP] <startScan> args: {service_uuids: [0000acf0-0000-1000-8000-00805f9b34fb], mac_addresses: [], allow_duplicates: false, android_scan_mode: 2, android_uses_fine_location: false}
D/[FBP-Android](  532): [FBP-Android] onMethodCall: startScan
E/AndroidRuntime(  532): FATAL EXCEPTION: main
E/AndroidRuntime(  532): Process: com.lifesparktech.walk, PID: 532
E/AndroidRuntime(  532): java.lang.NoSuchMethodError: No virtual method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(  532): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.fetchFilters(FlutterBluePlusPlugin.java:1179)
E/AndroidRuntime(  532): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.onMethodCall(FlutterBluePlusPlugin.java:310)
E/AndroidRuntime(  532): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(  532): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(  532): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(  532): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source)
E/AndroidRuntime(  532): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(  532): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  532): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(  532): 	at android.app.ActivityThread.main(ActivityThread.java:5597)
E/AndroidRuntime(  532): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  532): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(  532): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime(  532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
I/AndroidRuntime(  532): To Report FATAL to activityManagerService
I/AndroidRuntime(  532): Finished reporting FATAL to activityManagerService
I/Process (  532): Sending signal. PID: 532 SIG: 9
I/Kernel  (  532): [47536.302831]Mali<2>:
Lost connection to device.
Exited (sigterm)
```

**Comment by chipweinberger** [comment]
this is fixed. update
