### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by project2021-code** [boskokg/flutter_blue_plus#541]
### FlutterBluePlus Version

1.14.17

### Flutter Version

3.13.2

### What OS?

Android

### OS Version

Android 8

### What happened?

GATT stopped working, the last working version is 1.14.16

### Logs

```shell
D/[FBP-Android](12869): [FBP-Android] onMethodCall: setLogLevel
D/[FBP-Android](12869): [FBP-Android] initializing BluetoothAdapter
D/[FBP-Android](12869): [FBP-Android] onMethodCall: getAdapterState
D/[FBP-Android](12869): [FBP-Android] onMethodCall: getConnectedSystemDevices
D/BluetoothManager(12869): getConnectedDevices
D/[FBP-Android](12869): [FBP-Android] onMethodCall: startScan
D/BluetoothAdapter(12869): STATE_ON
D/BluetoothAdapter(12869): STATE_ON
D/BluetoothLeScanner(12869): Start Scan with callback
D/BluetoothLeScanner(12869): onScannerRegistered() - status=0 scannerId=6 mScannerId=0
D/[FBP-Android](12869): [FBP-Android] onMethodCall: stopScan
D/BluetoothAdapter(12869): STATE_ON
D/BluetoothAdapter(12869): STATE_ON
D/BluetoothLeScanner(12869): Stop Scan with callback
D/[FBP-Android](12869): [FBP-Android] onMethodCall: connect
D/BluetoothGatt(12869): connect() - device: 30:AE:A4:28:2C:CE, auto: false
D/BluetoothAdapter(12869): isSecureModeEnabled
D/BluetoothGatt(12869): registerApp()
D/BluetoothGatt(12869): registerApp() - UUID=b5269f7c-d564-4548-847a-4eeb992c82dd
D/BluetoothGatt(12869): onClientRegistered() - status=0 clientIf=6
D/BluetoothGatt(12869): onClientConnectionState() - status=0 clientIf=6 device=30:AE:A4:28:2C:CE
D/[FBP-Android](12869): [FBP-Android] onConnectionStateChange: status: 0 (SUCCESS) newState: connected
D/[FBP-Android](12869): [FBP-Android] onMethodCall: connect
D/[FBP-Android](12869): [FBP-Android] already connected
D/[FBP-Android](12869): [FBP-Android] onMethodCall: requestMtu
D/BluetoothGatt(12869): configureMTU() - device: 30:AE:A4:28:2C:CE mtu: 185
D/BluetoothGatt(12869): onConnectionUpdated() - Device=30:AE:A4:28:2C:CE interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(12869): onConfigureMTU() - Device=30:AE:A4:28:2C:CE mtu=185 status=0
D/[FBP-Android](12869): [FBP-Android] onMtuChanged: mtu: 185 status: 0
D/[FBP-Android](12869): [FBP-Android] onMethodCall: getAdapterState
D/[FBP-Android](12869): [FBP-Android] onMethodCall: discoverServices
D/BluetoothGatt(12869): discoverServices() - device: 30:AE:A4:28:2C:CE
D/BluetoothGatt(12869): onSearchComplete() = Device=30:AE:A4:28:2C:CE Status=0
D/[FBP-Android](12869): [FBP-Android] onServicesDiscovered: count: 4 status: 0
W/BluetoothGatt(12869): Unhandled exception in callback
W/BluetoothGatt(12869): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.util.UUID.toString()' on a null object reference
W/BluetoothGatt(12869): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.uuid128(FlutterBluePlusPlugin.java:114)
W/BluetoothGatt(12869): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.bmBluetoothCharacteristic(FlutterBluePlusPlugin.java:1837)
W/BluetoothGatt(12869): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin.bmBluetoothService(FlutterBluePlusPlugin.java:1804)
W/BluetoothGatt(12869): 	at com.boskokg.flutter_blue_plus.FlutterBluePlusPlugin$4.onServicesDiscovered(FlutterBluePlusPlugin.java:1545)
W/BluetoothGatt(12869): 	at android.bluetooth.BluetoothGatt$1$5.run(BluetoothGatt.java:330)
W/BluetoothGatt(12869): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:789)
W/BluetoothGatt(12869): 	at android.bluetooth.BluetoothGatt.-wrap0(Unknown Source:0)
W/BluetoothGatt(12869): 	at android.bluetooth.BluetoothGatt$1.onSearchComplete(BluetoothGatt.java:326)
W/BluetoothGatt(12869): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:110)
W/BluetoothGatt(12869): 	at android.os.Binder.execTransact(Binder.java:682)
D/BluetoothGatt(12869): onConnectionUpdated() - Device=30:AE:A4:28:2C:CE interval=39 latency=0 timeout=500 status=0
D/[FBP-Android](12869): [FBP-Android] onMethodCall: disconnect
D/BluetoothGatt(12869): cancelOpen() - device: 30:AE:A4:28:2C:CE
D/BluetoothGatt(12869): onClientConnectionState() - status=0 clientIf=6 device=30:AE:A4:28:2C:CE
D/[FBP-Android](12869): [FBP-Android] onConnectionStateChange: status: 0 (SUCCESS) newState: disconnected
D/BluetoothGatt(12869): close()
D/BluetoothGatt(12869): unregisterApp() - mClientIf=6
D/[FBP-Android](12869): [FBP-Android] onMethodCall: disconnect
D/[FBP-Android](12869): [FBP-Android] already disconnected
```

**Comment by chipweinberger** [comment]
fixed 1.14.18
