### ISSUE TITLE
[Bug]: LateInitializationError: Field 'characteristic' has not been initialized. & PlatformException(discoverServices, device is disconnected, null, null)

### ISSUE THREAD

**Issue by widzinskaj** [boskokg/flutter_blue_plus#546]
### FlutterBluePlus Version

1.14.11

### Flutter Version

3.13.2

### What OS?

Android

### OS Version

Android 13

### What happened?

I had a version of  working application in Android Studio and I made .apk file. I don't know what changed, but suddenly, when I returned to work over the more developed version (which also worked!) I got the problem which didn't occured earlier.

As you can see from logs, I had a problem with discoverServices, but it doesn't stop the app. The problem occurs when I push the button and I obtain LateInitializationError. It appears when I push the button and it writes  to BluetoothCharacteristic a message to turn off the device. I don't know what happened, because the more developed version worked before making an .apk file.

It's my first more advanced application and I don't know where is the problem - Flutter Blue Plus library, configuration files...I really appreciate any help.

### Logs

```shell
Launching lib\main.dart on moto e13 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Debug service listening on ws://127.0.0.1:52746/5DAd2jR_dsQ=/ws
Syncing files to device moto e13...
D/[FBP-Android](15441): [FBP-Android] onMethodCall: setLogLevel
D/[FBP-Android](15441): [FBP-Android] initializing BluetoothAdapter
D/[FBP-Android](15441): [FBP-Android] onMethodCall: getAdapterState
I/mali_gralloc(15441): register: id=0x25f0000032d, importpid=-1
I/mali_gralloc(15441): register: id=0x25f0000032e, importpid=-1
W/Parcel  (15441): Expecting binder but got null!
W/ziparchive(15441): Unable to open '/system_ext/framework/unipnp-framework.dm': No such file or directory
W/ziparchive(15441): Unable to open '/system_ext/framework/unipnp-framework.dm': No such file or directory
I/mali_gralloc(15441): register: id=0x25f0000032f, importpid=-1
D/[FBP-Android](15441): [FBP-Android] onMethodCall: startScan
D/BluetoothAdapter(15441): isLeEnabled(): ON
D/BluetoothLeScanner(15441): onScannerRegistered() - status=0 scannerId=4 mScannerId=0
D/[FBP-Android](15441): [FBP-Android] onMethodCall: connect
D/BluetoothGatt(15441): connect() - device: 60:8A:10:50:FE:56, auto: false
D/BluetoothGatt(15441): registerApp()
D/BluetoothGatt(15441): registerApp() - UUID=4f608116-b935-4219-8b07-6e9ccdc5a7b4
D/BluetoothGatt(15441): onClientRegistered() - status=0 clientIf=5
D/[FBP-Android](15441): [FBP-Android] onMethodCall: discoverServices
E/flutter (15441): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(discoverServices, device is disconnected, null, null)
E/flutter (15441): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (15441): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (15441): <asynchronous suspension>
E/flutter (15441): #2      FlutterBluePlus._invokeMethod (package:flutter_blue_plus/src/flutter_blue_plus.dart:302:19)
E/flutter (15441): <asynchronous suspension>
E/flutter (15441): #3      BluetoothDevice.discoverServices (package:flutter_blue_plus/src/bluetooth_device.dart:172:7)
E/flutter (15441): <asynchronous suspension>
E/flutter (15441): 
I/mali_gralloc(15441): register: id=0x25f00000330, importpid=-1
D/BluetoothGatt(15441): onClientConnectionState() - status=0 clientIf=5 device=60:8A:10:50:FE:56
D/[FBP-Android](15441): [FBP-Android] onConnectionStateChange: status: 0 (SUCCESS) newState: connected
D/[FBP-Android](15441): [FBP-Android] onMethodCall: discoverServices
D/BluetoothGatt(15441): discoverServices() - device: 60:8A:10:50:FE:56
D/BluetoothGatt(15441): onSearchComplete() = Device=60:8A:10:50:FE:56 Status=0
D/[FBP-Android](15441): [FBP-Android] onServicesDiscovered: count: 5 status: 0
D/[FBP-Android](15441): [FBP-Android] onMethodCall: stopScan
D/BluetoothAdapter(15441): isLeEnabled(): ON
D/[FBP-Android](15441): [FBP-Android] onMethodCall: setNotification
D/BluetoothGatt(15441): setCharacteristicNotification() - uuid: 49535343-1e4d-4bd9-ba61-23c647249616 enable: true
D/[FBP-Android](15441): [FBP-Android] onDescriptorWrite: uuid: 00002902-0000-1000-8000-00805f9b34fb status: 0
D/BluetoothGatt(15441): onConnectionUpdated() - Device=60:8A:10:50:FE:56 interval=9 latency=0 timeout=512 status=0
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic
D/[FBP-Android](15441): [FBP-Android] onCharacteristicWrite: uuid: 49535343-8841-43f4-a8d4-ecbe34729bb3 status: 0
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic
D/[FBP-Android](15441): [FBP-Android] onCharacteristicWrite: uuid: 49535343-8841-43f4-a8d4-ecbe34729bb3 status: 0
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic
D/[FBP-Android](15441): [FBP-Android] onCharacteristicWrite: uuid: 49535343-8841-43f4-a8d4-ecbe34729bb3 status: 0
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic
D/[FBP-Android](15441): [FBP-Android] onCharacteristicWrite: uuid: 49535343-8841-43f4-a8d4-ecbe34729bb3 status: 0
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic
D/[FBP-Android](15441): [FBP-Android] onCharacteristicWrite: uuid: 49535343-8841-43f4-a8d4-ecbe34729bb3 status: 0

======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'characteristic' has not been initialized.

When the exception was thrown, this was the stack: 
#0      Battery.characteristic (package:breezebmsapp/Battery.dart)
#1      Battery.turnOffBMS (package:breezebmsapp/Battery.dart:228:5)
#2      _DeviceScreenState.build.<anonymous closure> (package:breezebmsapp/main.dart:2337:57)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#21     _invoke1 (dart:ui/hooks.dart:186:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#cdc93
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(240.0, 622.3)
  finalLocalPosition: Offset(137.1, 25.9)
  button: 1
  sent tap down
====================================================================================================
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onCharacteristicChanged: uuid: 49535343-1e4d-4bd9-ba61-23c647249616
D/[FBP-Android](15441): [FBP-Android] onMethodCall: writeCharacteristic

My discoverServices code:
Future<void> discoverServices() async {
    myList2 = []; 
    try {
      widget.device
          .discoverServices();
    } on Exception catch (e) {
      if (kDebugMode) {
        print('Cannot discover services' + e.toString());
      }
    }
    Future.delayed(const Duration(seconds: 1), () async {
      if (myList2.isEmpty && isDeviceClosed != true) {
        try {
          discoverServices();
        } on Exception catch (e) {
          if (kDebugMode) {
            print('Cannot discover services' + e.toString());
          }
        }
      } else if (myList2.isNotEmpty) {
        for (BluetoothCharacteristic c in myList2[0].characteristics) {
          if (c.uuid == uartrx) {
            await c.setNotifyValue(!c
                .isNotifying); 
            c.value.listen((event) {
              temp = temp + event; 
              widget.device.battery.processReceivedData(
                  temp); 
              if (mounted) {
                setState(() {
                  temp;
                });
              }
            });
            await c.read();
          } else if (c.uuid == uarttx) {
            // Sprawdzenie charakterystyki write
            characteristic = c;
            sendRepeatableTaskOldBMS(c);
          } else if (c.uuid == newbmsrx) {
            //read new BMS
            characteristicToNotify = c;
            await c.setNotifyValue(!c.isNotifying);
            c.value.listen((event) {
              temp = temp + event;
              widget.device.battery.processReceivedDataNewBMS(temp);
              if (mounted) {
                setState(() {
                  temp;
                });
              }
            });
          } else if (c.uuid == newbmstx) {
            //write new BMS
            characteristic = c;
            sendRepeatableTaskNewBMS(c);
          }
        }
      }
    });
  }
```

**Comment by chipweinberger** [comment]
seems like bugs in your own code. try asking chatgpt

**Comment by chipweinberger** [comment]
closing since these are not FBP bugs
