### ISSUE TITLE
[Help]: Why streams cannot be canceled?

### ISSUE THREAD

**Issue by EdwardRodr1guez** [boskokg/flutter_blue_plus#651]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.17.5

### Flutter Version

3.10

### What OS?

Android

### OS Version

Android 11

### Bluetooth Module

Arduino

### What is your problem?

When I pop any screen where I am listening any stream (related to the device connection or whatever) it does not matter what I code in the dispose override when I trying to cancel the stream, neither cancell neither force it to be null, nothing works. The final result is a log like shown below.
Also I check if the widget is mounted to proceed to cancel the stream but nothing... I dont know if I only should ignore that message and continue with my life

### Logs

```shell
: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _MainViewScreenViewState#e7dbe(lifecycle state: defunct, not mounted)
E/flutter (22954): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (22954): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (22954): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (22954): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1103:9)
E/flutter (22954): #1      State.setState (package:flutter/src/widgets/framework.dart:1138:6)
E/flutter (22954): #2      _MainViewScreenViewState.areMyDevicesAvailables.<anonymous closure>.<anonymous closure> (package:lightguard/screens/mainview/main_view_screen.dart:117:17)
E/flutter (22954): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (22954): #6      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
E/flutter (22954): #7      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (22954): #8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
E/flutter (22954): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (22954): #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (22954): #13     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (22954): #14     _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter (22954): #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #17     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (22954): #18     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (22954): #19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (22954): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (22954): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (22954):
I/chatty  (22954): uid=10705(io.lightguard.api) 1.ui identical 2 lines
E/flutter (22954): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _MainViewScreenViewState#e7dbe(lifecycle state: defunct, not mounted)
E/flutter (22954): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (22954): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (22954): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (22954): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1103:9)
E/flutter (22954): #1      State.setState (package:flutter/src/widgets/framework.dart:1138:6)
E/flutter (22954): #2      _MainViewScreenViewState.areMyDevicesAvailables.<anonymous closure>.<anonymous closure> (package:lightguard/screens/mainview/main_view_screen.dart:117:17)
E/flutter (22954): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (22954): #6      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
E/flutter (22954): #7      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (22954): #8      _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
E/flutter (22954): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (22954): #12     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter (22954): #13     _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter (22954): #14     _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter (22954): #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (22954): #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (22954): #17     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (22954): #18     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (22954): #19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (22954): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (22954): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (22954):
```

**Comment by chipweinberger** [comment]
check the example app. 

canceling in dispose should work
