### ISSUE TITLE
[Help]: Crashes apps run on Android 12 and above

### ISSUE THREAD

**Issue by Eloks7** [boskokg/flutter_blue_plus#905]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

Yes

### FlutterBluePlus Version

1.32.7

### Flutter Version

4.1.59+

### What OS?

Android

### OS Version

12+

### Bluetooth Module

Espressif esp32

### What is your problem?

My flutter app crashes when I try to find devices on Android 12 and above. but works fine in Android 11 and below.

### Logs

```shell
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1452, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.mycompany.bluetoothstarter/com.mycompany.bluetoothstarter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void c0.k$d.b(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference at android.app.ActivityThread.deliverResults(ActivityThread.java:5631) at android.app.ActivityThread.handleSendResult(ActivityThread.java:5675) at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2418) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8442) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:560) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void c0.k$d.b(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference at m.a.a(Unknown Source:24) at io.flutter.embedding.engine.c$c.h(Unknown Source:20) at io.flutter.embedding.engine.c.a(Unknown Source:14) at io.flutter.embedding.android.f.y(Unknown Source:59) at io.flutter.embedding.android.e.onRequestPermissionsResult(Unknown Source:10) at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9110) at android.app.Activity.dispatchActivityResult(Activity.java:8964) at android.app.ActivityThread.deliverResults(ActivityThread.java:5624) ... 13 more
```

**Comment by Eloks7** [comment]
Resolved.
It was an issue with the way my permissions were entered in the AndroidManifest.
